# Generated by Django 6.1 on 2026-08-14 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260812_1604'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cancellations', models.IntegerField(default=0)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unique_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('avg_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='movies_dail_date_95a7da_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', 'Page View'), ('BOOKING', 'Booking Created'), ('PAYMENT', 'Payment Completed'), ('CANCELLATION', 'Booking Cancelled'), ('REFUND', 'Refund Processed'), ('SEARCH', 'Search Performed'), ('REVIEW', 'Review Submitted')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.theater')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='movies_anal_event_t_0171fc_idx'), models.Index(fields=['movie', 'created_at'], name='movies_anal_movie_i_a5589c_idx'), models.Index(fields=['theater', 'created_at'], name='movies_anal_theater_6a4b95_idx'), models.Index(fields=['created_at'], name='movies_anal_created_5622ce_idx')],
            },
        ),
    ]
