# Generated by Django 6.1 on 2026-08-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_dailyreport_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_timings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['city'], name='movies_movi_city_33c988_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['theater'], name='movies_movi_theater_e85b8d_idx'),
        ),
    ]
