# Generated by Django 6.1 on 2026-08-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_genres_movie_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='languages',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, help_text='Movie language (e.g., English, Hindi)', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, help_text='Comma separated genres (e.g., Action, Drama)', max_length=255, null=True),
        ),
    ]
